export const ELEMENTS = [
  {
    id: 'pyro',
    name: 'Pyro',
    latin: 'Ignis',
    archon: 'Mavuika',
    color: '#ff6b35',
    colorDim: '#c44820',
    glow: 'rgba(255,107,53,0.4)',
    bg: 'linear-gradient(145deg,#1a0800,#2a0e00,#0d0300)',
    symbol: '🔥',
    sigil: '▲',
    keywords: ['Fire', 'Passion', 'Destruction', 'Sacred Flame'],
    desc: "The element of burning ambition. Pyro is the most aggressive element in Teyvat — it ignites, melts, and detonates. Nations touched by Pyro burn brightest and fall hardest.",
    lore: [
      { h: 'Nature of Fire', b: "Pyro is not mere heat — it is will made visible. The Pyro Archon Mavuika channels it as the Sacred Flame, a primal force older than nations. When two fire-touched souls fight side by side, their flames synchronize into something neither could conjure alone." },
      { h: 'Nightsoul Blessing', b: "Natlan's warriors discovered a deeper layer of Pyro: the Nightsoul. This primal resonance transcends normal Vision use, transforming the body into a living conduit that draws energy directly from the land's sacred fire rather than from personal ambition." },
      { h: 'Combat Role', b: "Pyro excels at triggering the most explosive reactions: Vaporize (2× or 1.5×), Melt (2× or 1.5×), Overloaded (AoE burst), and Burning (DoT field). A skilled Pyro user is an engine — they apply the element that makes every other element hit harder." },
    ],
  },
  {
    id: 'hydro',
    name: 'Hydro',
    latin: 'Aqua',
    archon: 'Focalors',
    color: '#4db8ff',
    colorDim: '#1a7ab8',
    glow: 'rgba(77,184,255,0.4)',
    bg: 'linear-gradient(145deg,#00101a,#001828,#00070f)',
    symbol: '💧',
    sigil: '◯',
    keywords: ['Water', 'Cleansing', 'Justice', 'Memory'],
    desc: "The element of flowing truth. Hydro enables — it is the primer that makes Electro arc further, makes Pyro explode larger, makes Cryo shatter. Without Hydro, most reactions go silent.",
    lore: [
      { h: 'The Flowing Truth', b: "Hydro is associated with memory and truth in Teyvat's cosmology. Fontaine's people were literally made of Hydro — their bodies carried elemental water as a divine condition, one the prophecy threatened to dissolve back into the primordial sea." },
      { h: 'Enabling Element', b: "Hydro's combat role is uniquely generative. It does not destroy on its own — it prepares. Wet status enables Freeze, Vaporize, Electro-Charged, and Bloom. A Hydro applier is the silent architect behind every team's reaction chain." },
      { h: 'Neuvillette & Sovereign Power', b: "The Hydro Dragon Sovereign Neuvillette holds power that predates the current Archon system. His tears — literally Hydro — reshape battlefields. He represents what elemental mastery looks like when divorced from human limitation." },
    ],
  },
  {
    id: 'anemo',
    name: 'Anemo',
    latin: 'Ventus',
    archon: 'Barbatos',
    color: '#70e8c0',
    colorDim: '#2aaa84',
    glow: 'rgba(112,232,192,0.4)',
    bg: 'linear-gradient(145deg,#001a12,#002a1c,#000f09)',
    symbol: '🌪',
    sigil: '~',
    keywords: ['Wind', 'Freedom', 'Song', 'Swirl'],
    desc: "The element of liberation. Anemo carries other elements across the battlefield, amplifying them and spreading their reach. Barbatos chose it as his element because wind cannot be owned.",
    lore: [
      { h: 'Wind Cannot Be Owned', b: "Barbatos chose Anemo not for its power but for its meaning. Wind has no master — it blows past kings and beggars alike. His nation, Mondstadt, embodies this: no ruling god, no imperial court, just knights sworn to protect the freedom of ordinary people." },
      { h: 'Swirl Mechanics', b: "Anemo's primary reaction, Swirl, takes an existing element on an enemy and spreads it to nearby targets. This makes Anemo a force multiplier: the same Pyro or Electro or Cryo application now hits five enemies instead of one. Kazuha and Venti are considered some of the game's most powerful supports because of this." },
      { h: 'Absorption', b: "Certain Anemo skills can absorb another element — an Anemo tornado can become a Hydro tornado or a Pyro vortex. This absorption represents the wind taking on the character of what it carries, a subtle nod to Barbatos's empathetic nature." },
    ],
  },
  {
    id: 'electro',
    name: 'Electro',
    latin: 'Fulgur',
    archon: 'Ei',
    color: '#c080ff',
    colorDim: '#7a3ab8',
    glow: 'rgba(192,128,255,0.4)',
    bg: 'linear-gradient(145deg,#0d0020,#160030,#060010)',
    symbol: '⚡',
    sigil: '↯',
    keywords: ['Lightning', 'Eternity', 'Superconduct', 'Quicken'],
    desc: "The element of persistence. Electro lingers — it arcs, it chains, it Superconduces away resistances. In the Dendro era, it unlocked an entirely new reaction tree that redefined team-building.",
    lore: [
      { h: 'The Eternity Paradox', b: "Ei chose Electro because lightning is instantaneous yet eternal — a single moment of perfect clarity. Her pursuit of eternity through stasis is reflected in the element: Electro interrupts, resets, and persists. It cannot be ignored the way Cryo or Hydro applications sometimes can." },
      { h: 'The Dendro Revolution', b: "Before Sumeru's patch, Electro was considered underpowered. Then Dendro arrived. Quicken enables Aggravate (Electro bonus damage) and Spread (Dendro bonus damage). Hyperbloom and Electrocharged became the backbone of the game's strongest team archetypes overnight." },
      { h: 'Superconduct', b: "Electro + Cryo creates Superconduct — it deals minor AoE damage but more importantly shreds Physical resistance by 40%. This reaction exists specifically to enable Physical DPS characters like Eula and Razor, making Electro a hidden support element in Physical comps." },
    ],
  },
  {
    id: 'dendro',
    name: 'Dendro',
    latin: 'Silva',
    archon: 'Nahida',
    color: '#88d840',
    colorDim: '#4a8a10',
    glow: 'rgba(136,216,64,0.4)',
    bg: 'linear-gradient(145deg,#041200,#081e00,#020800)',
    symbol: '🌿',
    sigil: '⊕',
    keywords: ['Nature', 'Wisdom', 'Growth', 'Bloom'],
    desc: "The newest element to arrive in Teyvat. Dendro rewrote the meta — its reactions are multiplicative where others are additive, and it enabled entirely new team compositions never before possible.",
    lore: [
      { h: 'The Absent Element', b: "For years, Dendro had no playable Archon and no playable characters. The element existed in the game as enemy attacks only. Its absence was lore-accurate: Nahida was imprisoned, and the God of Wisdom's corpse was used as a false deity. When she was freed, Dendro came alive." },
      { h: 'Irminsul and Memory', b: "Dendro is tied to Irminsul — the world tree storing all mortal memory. Nahida's power literally flows through the roots of knowledge. When she healed Irminsul, she proved that growth and repair are more powerful than stasis — a direct rebuke of Ei's eternity ideal." },
      { h: 'The Bloom Reaction Tree', b: "Dendro + Hydro = Bloom (AoE seed explosion). Bloom + Electro = Hyperbloom (homing seed missiles). Bloom + Pyro = Burgeon (AoE burst centered on character). Quicken + Electro = Aggravate. Quicken + Dendro = Spread. No other element has this branching reaction depth." },
    ],
  },
  {
    id: 'cryo',
    name: 'Cryo',
    latin: 'Gelu',
    archon: 'Tsaritsa',
    color: '#a8e8ff',
    colorDim: '#4898c0',
    glow: 'rgba(168,232,255,0.4)',
    bg: 'linear-gradient(145deg,#00101e,#001828,#00060e)',
    symbol: '❄',
    sigil: '✦',
    keywords: ['Ice', 'Preservation', 'Freeze', 'Shatter'],
    desc: "The element of crystalline preservation. Cryo freezes enemies in place, enabling free damage. Combined with Hydro, entire groups can be locked down. Combined with Electro, armor shatters.",
    lore: [
      { h: 'The Coldest Archon', b: "The Tsaritsa was once described as overflowing with love — and then Celestia took that love from her. What remains is the cold clarity of someone who has decided to burn the world's institutions down to free humanity from a predetermined script. Her element mirrors her: preserved, distant, crystalline, lethal." },
      { h: 'Freeze Compositions', b: "Cryo + Hydro = Freeze. Frozen enemies cannot move, cannot attack, and take 200% Shatter damage from Claymore and Plunging attacks. Freeze comps dominated early meta because of their near-perfect crowd control — a frozen enemy is a dead enemy." },
      { h: 'Melt and Superconduct', b: "Cryo enables Melt (Cryo+Pyro for up to 2× multiplier) and Superconduct (Cryo+Electro for 40% Physical shred). This makes Cryo one of the most versatile reaction elements — it slots into Pyro DPS teams, Physical teams, and its own Freeze comps equally well." },
    ],
  },
  {
    id: 'geo',
    name: 'Geo',
    latin: 'Terra',
    archon: 'Morax',
    color: '#f0c040',
    colorDim: '#a07010',
    glow: 'rgba(240,192,64,0.4)',
    bg: 'linear-gradient(145deg,#120800,#1e0e00,#080400)',
    symbol: '⛰',
    sigil: '◈',
    keywords: ['Earth', 'Contract', 'Crystallize', 'Shield'],
    desc: "The element of unbreakable foundations. Geo cannot trigger most reactions — it crystallizes. But Crystallize is unique: it creates elemental shields, turning offense into defense simultaneously.",
    lore: [
      { h: "The God Who Walked Away", b: "Morax is 6,000 years old — the oldest Archon, the survivor of the Archon War, the god who shaped Liyue's geography with his own hands. He willingly gave his Gnosis to the Tsaritsa and retired as a human, going by Zhongli, because he believed his people had grown strong enough to govern themselves." },
      { h: 'Crystallize Mechanics', b: "Geo cannot Swirl, Vaporize, or Melt. Instead, Geo + any element = Crystallize, spawning an elemental shard. Picking up the shard grants a 250-750 HP shield of that element's type. This is uniquely defensive — Geo turns every elemental encounter into a shield factory." },
      { h: 'Geo Resonance', b: "Two Geo characters in a team grant Geo Resonance: 15% damage bonus, 20% shield strength, and shields cause Geo DMG bonus. Zhongli's shield + a second Geo triggers what players call 'Petra stacking' — a fortress-offense playstyle that defines one of the game's most reliable team archetypes." },
    ],
  },
]