export const REACTIONS = {
  'pyro+hydro':    { name: 'Vaporize',       color: '#ff8c42', symbol: '💦🔥', mult: '1.5× / 2×',      desc: "One of the two multiplicative reactions. Hydro on Pyro deals 2× Vaporize; Pyro on Hydro deals 1.5×. The direction matters. Xiangling's Pyronado Vaporizing off a Xingqiu burst is the game's most iconic damage spike." },
  'hydro+pyro':    { name: 'Vaporize',       color: '#ff8c42', symbol: '💦🔥', mult: '1.5× / 2×',      desc: "One of the two multiplicative reactions. Hydro on Pyro deals 2× Vaporize; Pyro on Hydro deals 1.5×. The direction matters. Xiangling's Pyronado Vaporizing off a Xingqiu burst is the game's most iconic damage spike." },
  'pyro+cryo':     { name: 'Melt',           color: '#ffb060', symbol: '❄🔥',  mult: '1.5× / 2×',      desc: "The other multiplicative reaction. Pyro on Cryo = 2× Melt; Cryo on Pyro = 1.5×. Ganyu's Cryo Bloom hitting a Pyro-applied enemy for 2× damage is considered the highest single-hit damage ceiling in the game." },
  'cryo+pyro':     { name: 'Melt',           color: '#ffb060', symbol: '❄🔥',  mult: '1.5× / 2×',      desc: "The other multiplicative reaction. Pyro on Cryo = 2× Melt; Cryo on Pyro = 1.5×. Ganyu's Cryo Bloom hitting a Pyro-applied enemy for 2× damage is considered the highest single-hit damage ceiling in the game." },
  'pyro+electro':  { name: 'Overloaded',     color: '#ff4488', symbol: '⚡🔥',  mult: 'AoE DMG',        desc: "Pyro + Electro detonates in a Pyro explosion dealing AoE damage and knocking enemies back. Powerful but scattering — experienced players time Overloaded to blast enemies into corners rather than into the abyss." },
  'electro+pyro':  { name: 'Overloaded',     color: '#ff4488', symbol: '⚡🔥',  mult: 'AoE DMG',        desc: "Pyro + Electro detonates in a Pyro explosion dealing AoE damage and knocking enemies back. Powerful but scattering — experienced players time Overloaded to blast enemies into corners rather than into the abyss." },
  'pyro+dendro':   { name: 'Burning',        color: '#ff6020', symbol: '🌿🔥',  mult: 'DoT field',      desc: "Pyro + Dendro creates a Burning field that continuously deals Pyro DMG to anything standing in it. Burning enemies also have Pyro applied repeatedly — useful for enabling Vaporize and Melt chains but tricky to control the area." },
  'dendro+pyro':   { name: 'Burning',        color: '#ff6020', symbol: '🌿🔥',  mult: 'DoT field',      desc: "Pyro + Dendro creates a Burning field that continuously deals Pyro DMG to anything standing in it. Burning enemies also have Pyro applied repeatedly — useful for enabling Vaporize and Melt chains but tricky to control the area." },
  'hydro+cryo':    { name: 'Freeze',         color: '#88ddff', symbol: '💧❄',  mult: 'Hard CC',        desc: "The crowd-control king. Hydro + Cryo freezes enemies solid — they cannot move, attack, or dodge. Frozen enemies take 200% Shattered damage from Claymore/Geo attacks. Freeze comps pair Ayaka or Ganyu with Mona or Kokomi to lock entire rooms." },
  'cryo+hydro':    { name: 'Freeze',         color: '#88ddff', symbol: '💧❄',  mult: 'Hard CC',        desc: "The crowd-control king. Hydro + Cryo freezes enemies solid — they cannot move, attack, or dodge. Frozen enemies take 200% Shattered damage from Claymore/Geo attacks. Freeze comps pair Ayaka or Ganyu with Mona or Kokomi to lock entire rooms." },
  'hydro+electro': { name: 'Electro-Charged', color: '#a060ff', symbol: '💧⚡', mult: 'Chain DMG',      desc: "Hydro + Electro creates a persistent Electro-Charged state that deals Electro DMG every second and arcs to nearby Wet enemies. In water or with grouping, one EC application damages an entire mob pack simultaneously — terrifying in Abyss." },
  'electro+hydro': { name: 'Electro-Charged', color: '#a060ff', symbol: '💧⚡', mult: 'Chain DMG',      desc: "Hydro + Electro creates a persistent Electro-Charged state that deals Electro DMG every second and arcs to nearby Wet enemies. In water or with grouping, one EC application damages an entire mob pack simultaneously — terrifying in Abyss." },
  'hydro+dendro':  { name: 'Bloom',          color: '#60d840', symbol: '💧🌿',  mult: 'Seed burst',     desc: "The reaction that spawned an entire meta. Hydro + Dendro creates a Dendro Core — a glowing seed that explodes after a moment for massive AoE Dendro DMG. Cores can then be reacted further: Electro → Hyperbloom (homing missile), Pyro → Burgeon (AoE blast)." },
  'dendro+hydro':  { name: 'Bloom',          color: '#60d840', symbol: '💧🌿',  mult: 'Seed burst',     desc: "The reaction that spawned an entire meta. Hydro + Dendro creates a Dendro Core — a glowing seed that explodes after a moment for massive AoE Dendro DMG. Cores can then be reacted further: Electro → Hyperbloom (homing missile), Pyro → Burgeon (AoE blast)." },
  'cryo+electro':  { name: 'Superconduct',   color: '#c0a0ff', symbol: '❄⚡',   mult: '-40% Phys RES',  desc: "Cryo + Electro deals minor AoE Cryo DMG but, critically, reduces all nearby enemies' Physical RES by 40% for 12s. This hidden utility reaction exists purely to enable Physical DPS archetypes — Eula, Razor, Fischl battery comps all rely on it." },
  'electro+cryo':  { name: 'Superconduct',   color: '#c0a0ff', symbol: '❄⚡',   mult: '-40% Phys RES',  desc: "Cryo + Electro deals minor AoE Cryo DMG but, critically, reduces all nearby enemies' Physical RES by 40% for 12s. This hidden utility reaction exists purely to enable Physical DPS archetypes — Eula, Razor, Fischl battery comps all rely on it." },
  'electro+dendro': { name: 'Quicken',       color: '#a8e840', symbol: '⚡🌿',  mult: 'Aggravate/Spread', desc: "Electro + Dendro creates the Quicken state, which enables two further reactions: Aggravate (Electro hits deal bonus Electro DMG) and Spread (Dendro hits deal bonus Dendro DMG). Both are additive flat damage bonuses that scale with Elemental Mastery — enabling EM builds as primary DPS for the first time." },
  'dendro+electro': { name: 'Quicken',       color: '#a8e840', symbol: '⚡🌿',  mult: 'Aggravate/Spread', desc: "Electro + Dendro creates the Quicken state, which enables two further reactions: Aggravate (Electro hits deal bonus Electro DMG) and Spread (Dendro hits deal bonus Dendro DMG). Both are additive flat damage bonuses that scale with Elemental Mastery — enabling EM builds as primary DPS for the first time." },
  'anemo+pyro':    { name: 'Swirl',          color: '#ff6b35', symbol: '🌪🔥',  mult: 'Spread+Shred',   desc: "Anemo absorbs and spreads Pyro to all nearby enemies, dealing Pyro DMG to each. Swirl also shreds Elemental RES by 40% if the Anemo character has the Viridescent Venerer artifact set — the most powerful support debuff in the game." },
  'anemo+hydro':   { name: 'Swirl',          color: '#4db8ff', symbol: '🌪💧',  mult: 'Spread+Shred',   desc: "Anemo spreads Hydro to all nearby enemies. With VV set, shreds Hydro RES by 40%. Sucrose and Kazuha are the primary Swirl supports, with Kazuha's Elemental Mastery snapshot being one of the game's most complex interaction chains." },
  'anemo+electro': { name: 'Swirl',          color: '#c080ff', symbol: '🌪⚡',  mult: 'Spread+Shred',   desc: "Anemo spreads Electro to all nearby enemies. Swirl + VV debuff is particularly potent in Electro-based teams where the 40% RES shred applies to all subsequent Electro reactions in the chain." },
  'anemo+cryo':    { name: 'Swirl',          color: '#a8e8ff', symbol: '🌪❄',   mult: 'Spread+Shred',   desc: "Anemo spreads Cryo to all nearby enemies. Freeze teams use this to apply Cryo aura to mobs before a Hydro unit freezes them all simultaneously. The spread radius makes Venti's burst a Freeze team's best friend." },
  'anemo+dendro':  { name: 'Swirl',          color: '#88d840', symbol: '🌪🌿',  mult: 'Spread',         desc: "Anemo can spread Dendro, though this is rarer in practice. Burning + Anemo spread creates an area-denial fire field, and in Natlan team comps, Anemo spreading Dendro enables unique Quicken + Swirl hybrid plays." },
  'geo+pyro':      { name: 'Crystallize',    color: '#f0c040', symbol: '⛰🔥',  mult: 'Pyro Shield',    desc: "Geo + any element = Crystallize, spawning a crystal shard. Picking it up grants a 1-3s elemental shield of that element's type. Pyro Crystallize creates a Pyro shield that absorbs incoming Pyro damage — valuable against fire-heavy floors." },
  'geo+hydro':     { name: 'Crystallize',    color: '#4db8ff', symbol: '⛰💧',  mult: 'Hydro Shield',   desc: "Hydro Crystallize shard grants a Hydro shield. While less commonly targeted than other Crystallize types, it matters in Hydro-heavy content and is a free mini-shield pickup for any team running a Geo character." },
  'geo+cryo':      { name: 'Crystallize',    color: '#a8e8ff', symbol: '⛰❄',   mult: 'Cryo Shield',    desc: "Cryo Crystallize is sought-after for Freeze teams — it provides a Cryo shield while keeping the Cryo aura on enemies intact for subsequent Freeze applications. Zhongli teams in Cryo comps intentionally farm these shards." },
  'geo+electro':   { name: 'Crystallize',    color: '#c080ff', symbol: '⛰⚡',  mult: 'Electro Shield', desc: "Electro Crystallize creates a free Electro shield. In Electro-heavy teams, this provides occasional chip defense without interrupting the reaction chain. Less game-changing than the Electro RES shred approach, but free sustain is never wasted." },
  'geo+dendro':    { name: 'Crystallize',    color: '#88d840', symbol: '⛰🌿',  mult: 'Dendro Shield',  desc: "Dendro Crystallize is rarer but functional — a Dendro shield absorbs incoming Dendro DMG, useful in Burning-heavy content. The shard appears near where the reaction occurred, requiring the player to move to collect it." },
  'geo+anemo':     { name: 'No Reaction',    color: '#666',    symbol: '—',    mult: 'None',           desc: "Geo and Anemo do not react with each other. Geo cannot be Swirled, and Anemo cannot be Crystallized. This is intentional — both are 'neutral' elements that modify other reactions rather than being modified themselves." },
  'pyro+pyro':     { name: 'Resonance',      color: '#ff6b35', symbol: '🔥🔥', mult: '+25% ATK',       desc: "Two Pyro characters in the team trigger Pyro Resonance: all party members gain +25% ATK. The simplest and most universally powerful resonance, which is why double-Pyro appears in nearly every meta team composition." },
  'hydro+hydro':   { name: 'Resonance',      color: '#4db8ff', symbol: '💧💧', mult: '+25% HP',        desc: "Hydro Resonance grants +25% max HP to all party members. With Furina's kit scaling off HP and triggering healing-based buffs, double-Hydro Resonance became the backbone of the Furina team archetype." },
  'cryo+cryo':     { name: 'Resonance',      color: '#a8e8ff', symbol: '❄❄',  mult: '+15% CRIT vs frozen', desc: "Cryo Resonance grants 15% CRIT Rate against enemies affected by Cryo or Frozen. In pure Cryo/Freeze teams, this is a free CRIT Rate sub-stat — allowing characters to invest in CRIT DMG instead." },
  'electro+electro': { name: 'Resonance',    color: '#c080ff', symbol: '⚡⚡',  mult: 'Energy Recharge', desc: "Electro Resonance triggers a mini-particle generator: when Electro reactions occur, a flat Energy particle is created every 5s. In teams with high Electro uptime, this effectively solves Energy Recharge needs, freeing artifact slots for offensive stats." },
  'anemo+anemo':   { name: 'Resonance',      color: '#70e8c0', symbol: '🌪🌪',  mult: '+10% SPD -5% Stamina', desc: "Anemo Resonance increases movement speed by 10% and reduces Stamina consumption for dashing and gliding by 15%. Primarily a quality-of-life resonance — helpful in exploration but rarely worth the team slot over a combat-focused option." },
  'geo+geo':       { name: 'Resonance',      color: '#f0c040', symbol: '⛰⛰',  mult: '+15% Geo DMG + Shield', desc: "Geo Resonance grants +15% DMG to shielded characters and empowers Crystallize shards to deal Geo DMG on pickup. With Zhongli's near-permanent shield, double-Geo teams maintain the damage buff almost 100% of uptime." },
  'dendro+dendro': { name: 'Resonance',      color: '#88d840', symbol: '🌿🌿',  mult: '+50 EM',         desc: "Dendro Resonance grants +50 Elemental Mastery. In reaction-focused Dendro teams where EM is the primary stat, this resonance effectively gives every team member a free EM sands substat — significant in Bloom and Hyperbloom comps." },
}

export function getReaction(a, b) {
  if (a === b) return REACTIONS[`${a}+${a}`] || null
  return REACTIONS[`${a}+${b}`] || REACTIONS[`${b}+${a}`] || null
}

export const EL = ['pyro', 'hydro', 'anemo', 'electro', 'dendro', 'cryo', 'geo']